zeebe:
   client:
      broker:
          gateway-address: 127.0.0.1:26500
      cloud:
          cluster-id: bae5bfa3-3e93-4de7-b7af-05cb4d65b377
          client-id: POV2A0sWGNkFIF6r2PM.ObGNG4GnoEXj
          region: bru-2

vanillabp:
  adapters:
    camunda8:
      resources-path: processes/camunda8
