zeebe:
   client:
      cloud:
          cluster-id: to-be-defined-by-system-property
          client-id: to-be-defined-by-system-property
          client-secret: to-be-defined-by-system-property
          region: bru-2

application:
   processes-location: camunda8-processes
