spring:
   application:
      name: blueprint
   main:
      allow-bean-definition-overriding: true
   datasource:
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      jdbc-batch-processing: false
